---
title: "This is the title"
format:
  # latex: default
  html:
    keep-md: true
knit: quarto render
---

<caption> \(#tab:foobar) Here is the caption</caption>


```{r, eval=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
library(gt)
library(tidyverse)
library(glue)

# Define the start and end dates for the data range
start_date <- "2010-06-07"
end_date <- "2010-06-14"

# Create a gt table based on preprocessed
# `sp500` table data
sp500 %>%
  dplyr::filter(date >= start_date & date <= end_date) %>%
  dplyr::select(-adj_close) %>%
  gt() %>%
  tab_header(
    title = "S&P 500",
    subtitle = glue::glue("{start_date} to {end_date}")
  ) %>%
  fmt_date(
    columns = vars(date),
    date_style = 3
  ) %>%
  fmt_currency(
    columns = vars(open, high, low, close),
    currency = "USD"
  ) %>%
  fmt_number(
    columns = vars(volume),
    suffixing = TRUE
  )
```

```{r mytable, echo=FALSE}
library(modelsummary)
mod <- lm(hp ~ mpg, mtcars)
msummary(mod, title = 'This title describes the content of this table. {#tbl:content}')
```
