# working-directory
# rust version / toolchain
# out-dir

name: 'Build Launcher'
description: 'Builds the Quarto Launcher'
runs:
  using: "composite"
  steps: 
    - uses: actions/checkout@v4
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.63.0
        override: true
        components: rustfmt, clippy
    - uses: actions-rs/cargo@v1
      working-directory: package/launcher
      with:
        command: build
        args: --release --all-features
