#!/bin/bash


# This file contains the global configuration for the quarto configuration
#
# The configuration is used both as a local runtime version of Quarto for developers
# but it also used when packaging (e.g. run configure.sh, then prepare-dist.sh, then package.sh)
# deno_dom should match release at https://github.com/b-fuze/deno-dom/releases

# Binary dependencies
export DENO=v1.33.2
export DENO_DOM=v0.1.35-alpha-artifacts
export PANDOC=3.1.5
export DARTSASS=1.55.0
export ESBUILD=0.18.15
export TYPST=0.6.0

# Bootstrap dependencies from bslib
# (use commit hash from bslib repo)
export BOOTSTRAP=8dc31b40bd9b387c4a3c36ac1f63bb853037cba6
export BOOTSTRAP_FONT=1.10.5
export BOOTSWATCH=5.2.3

# javascript HTML dependencies
export ANCHOR_JS=5.0.0
export POPPER_JS=2.11.7
export CLIPBOARD_JS=2.0.11
export TIPPY_JS=6.3.7
export PDF_JS=2.8.335
# Using commit to fix https://github.com/quarto-dev/quarto-cli/issues/2430 - revert to using a release tag when included
export REVEAL_JS=e281b3234e7991283ce4dcca705dd9a6a9ebe5d2
export REVEAL_JS_MENU=2.1.0
export REVEAL_JS_CHALKBOARD=a88c134e2cf3c7780448db003e7329c3cbd8cfb4
export REVEAL_JS_PDFEXPORT=2.0.1
export LIST_JS=2.3.1
export DAY_JS=1.11.7
export ZENSCROLL_JS=4.0.2
export GITHUB_MARKDOWN_CSS=5.2.0

# javascript search dependencies
export AUTOCOMPLETE_JS=1.9.2
export FUSE_JS=6.6.2
export ALGOLIA_SEARCH_JS=4.5.1
export ALGOLIA_SEARCH_INSIGHTS_JS=2.0.3


# Quarto Info Version
export QUARTO_VERSION=1.4
export QUARTO_NAME=Quarto
export QUARTO_BUILD_RUN_OFFSET=-2030

# Folder names. These are not the same as paths (those variable names end in _PATH).
#     See set_package_paths .sh and .bat for these in context of full paths.
#     See the configure .sh and .cmd scripts for overrides.
export QUARTO_PACKAGE_DIR=package
export QUARTO_DIST_DIR=dist
export QUARTO_SHARE_DIR=share
export QUARTO_BIN_DIR=bin
export QUARTO_SRC_DIR=src
export QUARTO_OUT_DIR=out

# Quarto MSI upgrade code
# Altering this will change upgrade behavior of the windows installer
# so be sure you know what you're doing before you change it
# We use a dynamic product ID for every build (forcing a major upgrade)
# so this upgrade code is the only thing that connects different versions
# of this installed product (and permits upgrades).
export QUARTO_MSI_UPGRADE_CODE=98fb2e98-96b0-46e1-a6fd-94171233d11b
