#!/bin/bash


# This file contains the global configuration for the quarto configuration
#
# The configuration is used both as a local runtime version of Quarto for developers
# but it also used when packaging (e.g. run configure.sh, then prepare-dist.sh, then package.sh)


# Dependency versions
export PANDOC=2.11.2
export DENO=v1.4.6
export TINYTEX=v2020.10

# Version
export VERSION=0.1

# Quarto Command Global deno flags
export DENO_OPTIONS="--unstable --allow-read --allow-write --allow-run --allow-env"

# Configuration Target Directories
export WORKING_DIR=dist
export SHARE_DIR=share
export BIN_DIR=bin