title: "Your question in one sentence (e.g., How do I render a document with Quarto 2?)"
labels: ["q2"]
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the Quarto 2 discussions!
        We are always happy to hear feedback from our users.

        This category is for questions about **Quarto 2**, version 2 of Quarto.
        Quarto 2 is experimental and it is not ready for production use.
        Its source code is at https://github.com/quarto-dev/q2 and its command-line program is `q2`.

        - If your question is about **Quarto 1**, version 1 of the `quarto` command-line program, please use the [Q&A (Q1) GitHub Discussions](https://github.com/quarto-dev/quarto-cli/discussions/categories/q-a-q1).
        - If you're reporting a bug in **Quarto 2**, please open an issue at https://github.com/quarto-dev/q2/issues
        - If you want to ask for a feature, please use the [Feature Requests GitHub Discussions](https://github.com/quarto-dev/quarto-cli/discussions/categories/feature-requests).

        First, please check [Quarto 2 Issues](https://github.com/quarto-dev/q2/issues) and [Q&A (Q2) GitHub Discussions](https://github.com/quarto-dev/quarto-cli/discussions/categories/q-a-q2) to see if your question has already been asked.
        If it has, please consider adding a comment to the existing discussion instead of creating a new one.

        After checking, if you are not sure if your question has already been asked, please create a new discussion.
        We look forward to hearing from you.

        Finally, try to describe the best you can what you want to achieve or what is your issue, especially by providing a complete self-contained reproducible example (consider reading our ["Bug Reports" guide](https://quarto.org/bug-reports.html)).
        This will help us to understand your question and answer it.

        `````md
        ````qmd
        ---
        title: "Reproducible Quarto Document"
        format: html
        ---

        This is a reproducible Quarto document using `format: html`.

        ![An image](image.png){#fig-placeholder}

        A reference to @fig-placeholder.

        The end.
        ````
        `````

        You can add some additional information that can help us to help you:

        - What Quarto 2 version are you using?
          You can find the version of Quarto 2 you used by running `q2 --version` in your terminal.
        - What operating system are you using?
          Linux Ubuntu 24.04, macOS 15.2, Windows 11, _etc._

        _Thank you for opening this discussion either to ask for help or to report a possible bug!_
  - type: textarea
    attributes:
      label: Description
      description: Start your question/report!
      placeholder: |
        You can include Quarto document code which includes code blocks like this:

        `````md
        ````qmd
        ---
        title: "Reproducible Quarto Document"
        format: html
        ---

        This is a reproducible Quarto document using `format: html`.

        ![An image](image.png){#fig-placeholder}

        A reference to @fig-placeholder.

        The end.
        ````
        `````

        ---

        ### Additional information that can help us to help you

        - What Quarto 2 version are you using?
          You can find the version of Quarto 2 you used by running `q2 --version` in your terminal.
        - What operating system are you using?
          Linux Ubuntu 24.04, macOS 15.2, Windows 11, _etc._
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        _Thank you for opening this discussion either to ask for help or to report a possible bug!_
