#!/bin/bash
NIXARCH=$(uname -m)
if [[ $NIXARCH == "x86_64" ]]; then
  ARCH_DIR=x86_64
elif [[ $NIXARCH == "aarch64" ]]; then
  ARCH_DIR=aarch64
else
  echo "configure script failed: unrecognized architecture " ${NIXARCH}
  exit 1
fi

./${ARCH_DIR}/pandoc "$@"