---
title: <%= title %> Template
format:
  <%= name %>-pdf:
    keep-tex: true  
  <%= name %>-html: default
author:
  - name: Sarah Malloc
    affiliations:
      - name: An Organization
        department: The Department
        address: 1 Main St
        city: Boston
        country: USA
        postal-code: 02210-1022
      - A second affilication
    orcid: 0000-0000-0000-0000
    email: sm@example.org
    url: https://example.org/
  - name: Eliza Dealloc
    affiliations:
      - Another Affiliation
abstract: |
  This document is a template demonstrating the <%= title %> format.
keywords: [template, demo]
reference-section-title: References
bibliography: bibliography.bib  
---

## Introduction {#sec-intro}

*TODO* Create a template that demonstrates the appearance and formatting, layout, and functionality of your journal format. It is often useful to use the example template available from the journal publisher, porting that to markdown for this template.

## About Quarto Extensions formats And Quarto Journals Article

*TODO* Learn more usin the following resources

- [Creating Formats](https://quarto.org/docs/extensions/formats.html) in Quarto as part of the [Extensions](https://quarto.org/docs/extensions/) mechanism.
- [Journals Articles](https://quarto.org/docs/journals/) for Quarto.

## Style Guide

*TODO* If a style guide is available from the publisher, consider including that in a `style-guide` folder for reference.

### PDF and HTML Output

*TODO* Test HTML output for your journal format. When possible, implement markdown support for journal LaTeX specific commands or environments, which makes producing multiple formats from the same document possible [@CameronTrivedi2013].

{{< pagebreak >}}

