name: Bug report
description: Report an error or unexpected behavior you saw while using this package
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Welcome to the quarto GitHub repo!
        We are always happy to hear feedback from our users.

        To file a _bug report_, please follow these instructions carefully: <https://yihui.org/issue/#bug-reports>
        Also, please complete and keep the checklist below in your issue. This helps you know what to check for opening a good issue report. It also helps know that you've have done the common steps that can solve your potential issue.
        At last, if you have posted the same issue elsewhere, please mention it here, with a link to the other issue.
  - type: textarea
    attributes:
      label: Bug description
      description: Please describe the bug.
      placeholder: |
        You can include markdown code blocks which includes code blocks like this:

        ````md
        ```py
        print("Hello Quarto!")
        ```
        ````

  - type: checkboxes
    attributes:
      label: Checklist
      description: |
        When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:
      options:
        - label: "[formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?"
        - label: included a minimal, self-contained, and reproducible example?
        - label: documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
        - label: documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
        - label: documented which operating system you're running? If on Linux, please provide the specific distribution as well.
        - label: upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?
