#!/bin/bash
set -e

# detect whether running as root (per machien installation)
# if per machine (run without sudo):

if [[ $EUID -eq 0 ]]; then
ln -fs /opt/quarto/bin/quarto /usr/local/bin/quarto
else
ln -fs /opt/quarto/bin/quarto ~/bin/quarto
fi

exit 0