/*
* render-pdf.test.ts
*
* Copyright (C) 2020-2022 Posit Software, PBC
*
*/

import { docs } from "../../utils.ts";

import { testRender } from "./render.ts";

// Simple rendering tests
testRender(docs("templates/custom-template.qmd"), "pdf", true);
testRender(docs("templates/template-partial.qmd"), "pdf", true);
testRender(docs("templates/title-partial-html.qmd"), "html", false);

// ACM template test
testRender(docs("templates/acm/document.qmd"), "pdf", true);

// Elsevier template test
testRender(docs("templates/elsevier/document.qmd"), "pdf", true, [], {
  // deno-lint-ignore require-await
  teardown: async () => {
    // Clean up the SPL file that is generated by the elesevier class
    Deno.removeSync(docs("templates/elsevier/document.spl"));
  },
});

// ACS template test
testRender(docs("templates/acs/document.qmd"), "pdf", true);
