/*
 * report.ts
 *
 * The report stage: `findings.json` in, a self-contained `report.html` out.
 *
 * A dumb view — no grouping logic here, that all lives in aggregate.ts. Findings
 * are ordered by standard then severity, each row expands to its occurrences,
 * any column re-sorts, and every finding carries a copy-to-clipboard AI briefing
 * so a fix can be handed straight to an agent.
 *
 * Ported from the quarto-web harness (`_tools/axe/report.mjs`), HTML format
 * only: v1 keeps the drill-down report, and the console summary lives in cmd.ts.
 *
 * Copyright (C) 2026 Posit Software, PBC
 */

import { AxeFinding, AxeFindings } from "./schemas.ts";

function esc(value: unknown): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function plural(count: number, singular = "", many = "s"): string {
  return count === 1 ? singular : many;
}

// How many occurrences an AI briefing lists before it starts summarizing.
const kOccurrenceCap = 15;

const kBriefingPreamble =
  "This is from an axe-core accessibility audit of a website generated by " +
  "**Quarto**. Fixes usually belong in the Quarto *source* — a `.qmd`, " +
  "`_quarto.yml`, `brand.yml`, or a theme `.scss` — not in the generated " +
  "site HTML (it is overwritten every render). Some findings come from " +
  "Quarto's shared templates (navbar, footer, listings); those may warrant an " +
  "upstream Quarto issue rather than a local change.";

/** A markdown briefing for one finding, sized to paste into a chat. */
export function briefing(finding: AxeFinding): string {
  const shown = finding.occurrences.slice(0, kOccurrenceCap).map((occurrence) =>
    `- \`${occurrence.page}\` [${occurrence.cells.join(", ")}] — selector ` +
    `\`${occurrence.target}\`\n  \`\`\`html\n  ${occurrence.html}\n  \`\`\``
  ).join("\n");
  const hidden = finding.occurrences.length - kOccurrenceCap;
  const more = hidden > 0 ? `\n- …and ${hidden} more` : "";
  const fixNote = finding.label === "systemic"
    ? " Fixing the shared source fixes all of them."
    : "";
  return [
    `# Accessibility issue: ${finding.rule} — ${finding.standard} ` +
    `(${finding.impact})`,
    ``,
    kBriefingPreamble,
    ``,
    `- **Rule:** \`${finding.rule}\`${
      finding.help ? ` — ${finding.help}` : ""
    }`,
    `- **Standard:** ${finding.conformance || "—"}`,
    `- **Severity:** ${finding.impact}`,
    `- **Scope:** ${finding.label} — ${finding.pages.length} page${
      plural(finding.pages.length)
    }, ${finding.instances} occurrence${plural(finding.instances)}.${fixNote}`,
    `- **Problem:** ${finding.detail || finding.occurrences[0]?.detail || ""}`,
    ...(finding.helpUrl ? [`- **Reference:** ${finding.helpUrl}`] : []),
    `- **Finding id:** \`${finding.id}\` (look up the full record in ` +
    `\`findings.json\`)`,
    ``,
    `## Affected elements (${finding.occurrences.length}${
      hidden > 0 ? `, showing ${kOccurrenceCap}` : ""
    })`,
    shown + more,
    ``,
    `Please help me fix this in the Quarto source.`,
  ].join("\n");
}

const kStyles = `
  :root { color-scheme: light dark; --br:#d0d3d9; --mut:#5b6470; --bg:#fff; --fg:#1a1d21; --card:#f6f7f9; --hd:#eef1f4; }
  @media (prefers-color-scheme: dark){ :root{ --br:#333a44; --mut:#9aa4b0; --bg:#15171a; --fg:#e6e8eb; --card:#1e2126; --hd:#22262c; } }
  body { font: 15px/1.5 system-ui, sans-serif; margin: 0 auto; max-width: 1180px; padding: 1.5rem; color:var(--fg); background:var(--bg); }
  h1 { font-size: 1.5rem; margin: 0 0 .25rem; }
  .sub { color: var(--mut); margin:0 0 1rem; } .mut { color: var(--mut); }
  .warn { border-left:4px solid #c0392b; padding-left:.6rem; }
  table.findings { width:100%; border-collapse:collapse; }
  .findings > thead th { position:sticky; top:0; background:var(--hd); text-align:left; padding:.45rem .6rem;
    font-size:.85em; border-bottom:2px solid var(--br); cursor:pointer; user-select:none; white-space:nowrap; }
  .findings > thead th[data-key]::after { content:" \\2195"; color:var(--mut); font-size:.85em; }
  .findings > thead th[aria-sort=ascending]::after { content:" \\2191"; color:var(--fg); }
  .findings > thead th[aria-sort=descending]::after { content:" \\2193"; color:var(--fg); }
  tr.f > td { padding:.4rem .6rem; border-bottom:1px solid var(--br); vertical-align:top; cursor:pointer; }
  tr.f:hover > td { background:var(--card); }
  tr.f.open > td { background:var(--card); }
  td.std::before { content:"\\25B8 "; color:var(--mut); }
  tr.f.open td.std::before { content:"\\25BE "; }
  .rule { font-family: ui-monospace, monospace; font-weight:600; }
  .badge { font-size:.72em; padding:.05rem .4rem; border-radius:99px; border:1px solid var(--br); text-transform:uppercase; letter-spacing:.03em; }
  .badge.systemic { background:#fde8e8; color:#8a1c1c; border-color:#f5c2c2; }
  .badge.localized { background:#eef1f4; color:#3a4048; }
  .impact-critical,.impact-serious { background:#c0392b; color:#fff; border-color:#c0392b; }
  .impact-moderate { background:#e0892e; color:#fff; border-color:#e0892e; }
  .impact-minor { background:#8a939e; color:#fff; border-color:#8a939e; }
  td.num, th.num { text-align:right; font-variant-numeric:tabular-nums; }
  tr.d > td { padding:0 .6rem .6rem 1.6rem; background:var(--card); }
  table.occ { width:100%; border-collapse:collapse; font-size:.86em; }
  .occ th,.occ td { text-align:left; padding:.3rem .5rem; border-top:1px solid var(--br); vertical-align:top; }
  .occ th { color:var(--mut); font-weight:600; }
  .occ code { font-family: ui-monospace, monospace; font-size:.92em; word-break:break-all; }
  .occ .snip { color:var(--mut); } .cells { white-space:nowrap; color:var(--mut); }
  .findings > thead th:not([data-key]) { cursor:default; }
  td.act { white-space:nowrap; text-align:right; }
  .cp { font:inherit; font-size:.8em; padding:.1rem .45rem; border:1px solid var(--br); border-radius:6px; background:var(--bg); color:var(--fg); cursor:pointer; }
  .cp:hover { background:var(--hd); }
  .idchip { display:block; margin-top:.25rem; font-family:ui-monospace,monospace; font-size:.72em; color:var(--mut); cursor:pointer; }
  .idchip:hover { color:var(--fg); text-decoration:underline; }
  details.baselined { margin-top:1.5rem; border:1px solid var(--br); border-radius:8px; background:var(--card); }
  details.baselined > summary { cursor:pointer; padding:.6rem .8rem; color:var(--mut); font-size:.9em; user-select:none; }
  details.baselined[open] > summary { border-bottom:1px solid var(--br); }
  details.baselined table.findings { padding:.2rem; }
  details.baselined tr.f > td { opacity:.85; }
  td.why { color:var(--mut); font-size:.9em; }
  p.stale { border-left:4px solid #e0892e; padding-left:.6rem; font-size:.9em; }
  p.stale code { font-family:ui-monospace,monospace; }
`;

// Ranks are ascending (0 = worst), so severity and standard both default to
// ascending; reach columns default to biggest-first.
const kTableScript = `
  var AI = JSON.parse(document.getElementById('axe-ai').textContent);
  function copyText(text, el){
    navigator.clipboard.writeText(text).then(function(){
      if (!el) return; var was = el.textContent; el.textContent = 'copied \\u2713';
      setTimeout(function(){ el.textContent = was; }, 1200);
    });
  }
  var tbody = document.querySelector('#findings tbody');
  function pairs(){ var out=[], cur=null; Array.prototype.forEach.call(tbody.children, function(tr){
    if (tr.classList.contains('f')) { cur = {f:tr, d:null}; out.push(cur); } else if (cur) { cur.d = tr; } }); return out; }
  function onRowClick(e){
    var cp = e.target.closest('[data-copy]'); if (cp) { copyText(AI.briefings[cp.dataset.copy], cp); return; }
    var ci = e.target.closest('[data-copyid]'); if (ci) { copyText(ci.dataset.copyid, ci); return; }
    if (e.target.closest('a')) return;
    var row = e.target.closest('tr.f'); if (!row) return;
    var d = row.nextElementSibling;
    if (d && d.classList.contains('d')) { d.hidden = !d.hidden; row.classList.toggle('open'); }
  }
  Array.prototype.forEach.call(document.querySelectorAll('table.findings tbody'), function(tb){ tb.addEventListener('click', onRowClick); });
  var DEFAULT_DIR = { standard:1, class:1, rule:1, severity:1, pages:-1, instances:-1 };
  var sortKey = null, dir = 1;
  Array.prototype.forEach.call(document.querySelectorAll('#findings th[data-key]'), function(th){
    th.addEventListener('click', function(){
      var key = th.dataset.key, type = th.dataset.type || 'str';
      dir = (sortKey === key) ? -dir : DEFAULT_DIR[key]; sortKey = key;
      var ps = pairs();
      ps.sort(function(a,b){
        var va = a.f.dataset[key], vb = b.f.dataset[key];
        if (type === 'num') return (parseFloat(va) - parseFloat(vb)) * dir;
        return va.localeCompare(vb) * dir;
      });
      ps.forEach(function(p){ tbody.appendChild(p.f); if (p.d) tbody.appendChild(p.d); });
      Array.prototype.forEach.call(document.querySelectorAll('#findings th'), function(h){ h.removeAttribute('aria-sort'); });
      th.setAttribute('aria-sort', dir > 0 ? 'ascending' : 'descending');
    });
  });
`;

function occurrenceRows(finding: AxeFinding): string {
  return finding.occurrences.map((occurrence) =>
    `<tr><td>${esc(occurrence.page)}</td>` +
    `<td class="cells">${occurrence.cells.map(esc).join("<br>")}</td>` +
    `<td><code>${esc(occurrence.target)}</code></td>` +
    `<td><code class="snip">${esc(occurrence.html)}</code></td>` +
    `<td>${esc(occurrence.detail)}</td></tr>`
  ).join("");
}

function findingRows(findings: AxeFinding[], showWhy: boolean): string {
  return findings.map((finding) => {
    const why = showWhy
      ? `\n  <td class="why">${esc(finding.baselineNote ?? "")}</td>`
      : "";
    const columns = showWhy ? 9 : 8;
    return `<tr class="f" data-standard="${finding.standardRank}" ` +
      `data-severity="${finding.severityRank}" ` +
      `data-rule="${esc(finding.rule)}" ` +
      `data-class="${finding.label === "systemic" ? 0 : 1}" ` +
      `data-pages="${finding.pages.length}" ` +
      `data-instances="${finding.instances}">
  <td class="std" title="${esc(finding.conformance)}">${
        esc(finding.standard)
      }</td>
  <td><span class="badge impact-${finding.impact}">${
        esc(finding.impact)
      }</span></td>
  <td><code class="rule">${esc(finding.rule)}</code></td>
  <td><span class="badge ${finding.label}">${finding.label}</span></td>
  <td class="num">${finding.pages.length}</td>
  <td class="num">${finding.instances}</td>
  <td class="dcell">${esc(finding.detail || finding.examples[0])}</td>${why}
  <td class="act"><button class="cp" data-copy="${
        esc(finding.id)
      }" title="Copy an AI briefing (markdown) for this finding">copy</button><code class="idchip" data-copyid="${
        esc(finding.id)
      }" title="Copy this finding's id">${esc(finding.id)}</code></td></tr>
<tr class="d" hidden><td colspan="${columns}">
  <table class="occ"><thead><tr><th>page</th><th>cells (width·theme)</th><th>selector</th><th>element</th><th>detail</th></tr></thead>
  <tbody>${occurrenceRows(finding)}</tbody></table></td></tr>`;
  }).join("\n");
}

function tableHead(showWhy: boolean): string {
  return `<thead><tr>
  <th data-key="standard" data-type="num">standard</th>
  <th data-key="severity" data-type="num">severity</th>
  <th data-key="rule" data-type="str">rule</th>
  <th data-key="class" data-type="num">class</th>
  <th class="num" data-key="pages" data-type="num">pages</th>
  <th class="num" data-key="instances" data-type="num">occurrences</th>
  <th>detail</th>${showWhy ? "\n  <th>why accepted</th>" : ""}
  <th title="Copy an AI briefing (markdown), or the finding id">AI</th>
</tr></thead>`;
}

/** Render `findings.json` as a self-contained HTML report. */
export function renderReport(results: AxeFindings): string {
  const newFindings = results.findings.filter((finding) => !finding.baselined);
  const baselined = results.findings.filter((finding) => finding.baselined);

  // JSON in a <script type="application/json">; escape `<` so the payload can't
  // terminate the block early.
  const aiData = JSON.stringify({
    briefings: Object.fromEntries(
      results.findings.map((finding) => [finding.id, briefing(finding)]),
    ),
  }).replace(/</g, "\\u003c");

  const notOk = results.notOkCells.length
    ? `<p class="warn"><strong>Non-OK cells (fail-closed — not counted as passing):</strong> ${
      results.notOkCells.map((cell) =>
        `${esc(cell.status)} ${esc(cell.page)} ${esc(cell.viewport)}·${
          esc(cell.theme)
        }`
      ).join("; ")
    }</p>`
    : "";

  const stale = results.baseline.stale;
  const staleNotice = stale.length
    ? `<p class="mut stale">↳ ${stale.length} baseline entr${
      stale.length === 1 ? "y" : "ies"
    } not seen in this scan — if this was a full-page scan they are resolved and can be pruned from <code>${
      esc(results.baseline.file)
    }</code>: ${
      stale.map((entry) => `<code>${esc(entry.id ?? entry.signature)}</code>`)
        .join(", ")
    }</p>`
    : "";

  const baselinedSection = baselined.length
    ? `<details class="baselined"><summary>Known / baselined — ${baselined.length} finding${
      plural(baselined.length)
    } accepted, suppressed from the list above</summary>
<table class="findings" id="baselined">${tableHead(true)}<tbody>
${findingRows(baselined, true)}
</tbody></table></details>`
    : "";

  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>axe site audit — ${esc(results.pagesScanned)} pages</title>
<style>${kStyles}</style></head><body>
<h1>axe site audit</h1>
<p class="sub">${esc(results.pagesScanned)} pages · ${esc(results.cells.ok)}/${
    esc(results.cells.total)
  } cells ok · axe-core ${esc(results.axeVersion ?? "unknown")} · generated ${
    esc(results.generated)
  }<br>
<strong>${newFindings.length} new finding${
    plural(newFindings.length)
  }</strong> shown below${
    baselined.length
      ? ` · ${baselined.length} baselined (known, collapsed)`
      : ""
  }.<br>
Sorted by standard, then severity — click any header to re-sort; click a row to see occurrences.
<strong>systemic</strong> = repeats from a shared source (fix once, fixes many) · <strong>localized</strong> = one-off. <strong>pages</strong> = distinct pages affected; <strong>occurrences</strong> = distinct elements.</p>
${notOk}
${staleNotice}
<table class="findings" id="findings">${tableHead(false)}<tbody>
${findingRows(newFindings, false)}
</tbody></table>
${baselinedSection}
<script id="axe-ai" type="application/json">${aiData}</script>
<script>${kTableScript}</script>
</body></html>
`;
}
