// This file is automatically generated by `quarto build-js`! Do not edit.

export type MaybeArrayOf<T> = (T | T[]);

export type SchemaObject = { [key: string]: string };

export type MathMethods = (
  | "plain"
  | "webtex"
  | "gladtex"
  | "mathml"
  | "mathjax"
  | "katex"
);

export type PandocFormatRequestHeaders = ((string)[])[];

export type PandocFormatOutputFile = (string | null);

export type PandocFormatFilters =
  ((string | { type: string; path: string } | { type: "citeproc" }))[];

export type PandocShortcodes = (string)[];

export type PageColumn = (
  | "body"
  | "body-outset"
  | "body-outset-left"
  | "body-outset-right"
  | "page"
  | "page-left"
  | "page-right"
  | "page-inset-left"
  | "page-inset-right"
  | "screen"
  | "screen-left"
  | "screen-right"
  | "screen-rightcolumn"
  | "screen-inset"
  | "screen-inset-shaded"
  | "screen-inset-left"
  | "screen-inset-right"
  | "margin"
);

export type NavigationItem = (string | {
  "aria-label"?: string;
  file?: string;
  href?: string;
  icon?: string;
  menu?: (NavigationItem)[];
  text?: string;
  url?: string;
});

export type ToolItem = {
  href?: string;
  icon?: string;
  menu?: (NavigationItem)[];
  text?: string;
};

export type Comments = (false | {
  giscus?: {
    "repo-id"?: string;
    "category-id"?: string;
    "reactions-enabled"?: boolean;
    "input-position"?: ("top" | "bottom");
    category?: string;
    loading?: "lazy";
    language?: string;
    mapping?: (("pathname" | "url" | "title" | "og:title") | string);
    repo: string;
    theme?: (
      | "light"
      | "light_high_contrast"
      | "light_protanopia"
      | "dark"
      | "dark_high_contrast"
      | "dark_protanopia"
      | "dark_dimmed"
      | "transparent_dark"
      | "preferred_color_scheme"
    );
  };
  hypothesis?: (boolean | {
    assetRoot?: string;
    branding?: {
      accentColor?: string;
      appBackgroundColor?: string;
      annotationFontFamily?: string;
      ctaBackgroundColor?: string;
      selectionFontFamily?: string;
    };
    enableExperimentalNewNoteButton?: boolean;
    externalContainerSelector?: string;
    focus?: {
      user: { displayName?: string; username?: string; userid?: string };
    };
    openSidebar?: boolean;
    requestConfigFromFrame?: { ancestorLevel?: number; origin?: string };
    showHighlights?: (boolean | ("always" | "never"));
    services?: ({
      apiUrl: string;
      authority: string;
      allowLeavingGroups?: boolean;
      enableShareLinks?: boolean;
      grantToken: string;
      groups?: ("$rpc:requestGroups" | (string)[]);
      icon?: string;
    })[];
    sidebarAppUrl?: string;
    theme?: ("classic" | "clean");
    usernameUrl?: string;
  });
  utterances?: {
    "issue-term"?: string;
    label?: string;
    repo: string;
    theme?: string;
  };
});

export type SocialMetadata = {
  "image-alt"?: string;
  "image-width"?: number;
  "image-height"?: number;
  description?: string;
  image?: string;
  title?: string;
};

export type PageFooterRegion = (string | (NavigationItem)[]);

export type SidebarContents = ((NavigationItem | string | {
  contents?: SidebarContents;
  section?: (string | null);
}))[];

export type ProjectPreview = {
  "watch-inputs"?: boolean;
  browser?: boolean;
  host?: string;
  navigate?: boolean;
  port?: number;
  timeout?: number;
};

export type Publish = { netlify?: (PublishRecord)[] };

export type PublishRecord = { id?: string; url?: string };

export type BaseWebsite = {
  "site-url"?: string;
  "site-path"?: string;
  "repo-url"?: string;
  "repo-subdir"?: string;
  "repo-branch"?: string;
  "repo-actions"?: MaybeArrayOf<("none" | "edit" | "source" | "issue")>;
  "reader-mode"?: boolean;
  "google-analytics"?: (string | {
    "tracking-id"?: string;
    "anonymize-ip"?: boolean;
    storage?: ("cookies" | "none");
    version?: (3 | 4);
  });
  "cookie-consent"?: (boolean | {
    "policy-url"?: string;
    "prefs-text"?: string;
    palette?: ("light" | "dark");
    style?: ("simple" | "headline" | "interstitial" | "standalone");
    type?: ("implied" | "express");
  });
  "body-header"?: string;
  "body-footer"?: string;
  "margin-header"?: MaybeArrayOf<string>;
  "margin-footer"?: MaybeArrayOf<string>;
  "page-navigation"?: boolean;
  "page-footer"?: (string | {
    border?: (boolean | string);
    background?: string;
    center?: PageFooterRegion;
    foreground?: string;
    left?: PageFooterRegion;
    right?: PageFooterRegion;
  });
  "open-graph"?:
    (boolean | ({ "site-name"?: string; locale?: string } & SocialMetadata));
  "twitter-card"?: (
    | boolean
    | ({
      "card-style"?: ("summary" | "summary_large_image");
      creator?: string;
      site?: string;
    } & SocialMetadata)
  );
  comments?: Comments;
  description?: string;
  favicon?: string;
  image?: string;
  navbar?: (boolean | {
    "logo-alt"?: string;
    "logo-href"?: string;
    "collapse-below"?: ("sm" | "md" | "lg" | "xl" | "xxl");
    background?: (
      | (
        | "primary"
        | "secondary"
        | "success"
        | "danger"
        | "warning"
        | "info"
        | "light"
        | "dark"
      )
      | string
    );
    collapse?: boolean;
    foreground?: (
      | (
        | "primary"
        | "secondary"
        | "success"
        | "danger"
        | "warning"
        | "info"
        | "light"
        | "dark"
      )
      | string
    );
    logo?: string;
    left?: (NavigationItem)[];
    pinned?: boolean;
    right?: (NavigationItem)[];
    search?: boolean;
    title?: (string | boolean);
  });
  search?: (boolean | {
    "collapse-after"?: number;
    "copy-button"?: boolean;
    algolia?: {
      "index-name"?: string;
      "application-id"?: string;
      "search-only-api-key"?: string;
      "analytics-events"?: boolean;
      "show-logo"?: boolean;
      "index-fields"?: {
        href?: string;
        section?: string;
        title?: string;
        text?: string;
      };
      params?: SchemaObject;
    };
    location?: ("navbar" | "sidebar");
    limit?: number;
    type?: ("overlay" | "textbox");
  });
  sidebar?: (
    | boolean
    | MaybeArrayOf<
      {
        "collapse-level"?: number;
        alignment?: ("left" | "right" | "center");
        background?: (
          | (
            | "primary"
            | "secondary"
            | "success"
            | "danger"
            | "warning"
            | "info"
            | "light"
            | "dark"
          )
          | string
        );
        border?: boolean;
        contents?: SidebarContents;
        foreground?: (
          | (
            | "primary"
            | "secondary"
            | "success"
            | "danger"
            | "warning"
            | "info"
            | "light"
            | "dark"
          )
          | string
        );
        footer?: MaybeArrayOf<string>;
        header?: MaybeArrayOf<string>;
        id?: string;
        logo?: string;
        pinned?: boolean;
        subtitle?: string;
        search?: boolean;
        style?: ("docked" | "floating");
        title?: (string | boolean);
        tools?: (ToolItem)[];
      }
    >
  );
  title?: string;
};

export type ChapterItem = (NavigationItem | {
  chapters?: (NavigationItem)[];
  part: string;
});

export type ChapterList = (ChapterItem)[];

export type CrossrefLabelsSchema = string;

export type EpubContributor = (
  | string
  | MaybeArrayOf<{ "file-as"?: string; role?: string; text?: string }>
);

export type FormatLanguage = {
  "toc-title-document"?: string;
  "toc-title-website"?: string;
  "callout-tip-caption"?: string;
  "callout-note-caption"?: string;
  "callout-warning-caption"?: string;
  "callout-important-caption"?: string;
  "callout-caution-caption"?: string;
  "section-title-abstract"?: string;
  "section-title-footnotes"?: string;
  "section-title-appendices"?: string;
  "code-summary"?: string;
  "code-tools-menu-caption"?: string;
  "code-tools-show-all-code"?: string;
  "code-tools-hide-all-code"?: string;
  "code-tools-view-source"?: string;
  "code-tools-source-code"?: string;
  "search-no-results-text"?: string;
  "copy-button-tooltip"?: string;
  "copy-button-tooltip-success"?: string;
  "repo-action-links-edit"?: string;
  "repo-action-links-source"?: string;
  "repo-action-links-issue"?: string;
  "search-matching-documents-text"?: string;
  "search-copy-link-title"?: string;
  "search-hide-matches-text"?: string;
  "search-more-match-text"?: string;
  "search-more-matches-text"?: string;
  "search-clear-button-title"?: string;
  "search-detached-cancel-button-title"?: string;
  "search-submit-button-title"?: string;
  "crossref-fig-title"?: string;
  "crossref-tbl-title"?: string;
  "crossref-lst-title"?: string;
  "crossref-thm-title"?: string;
  "crossref-lem-title"?: string;
  "crossref-cor-title"?: string;
  "crossref-prp-title"?: string;
  "crossref-cnj-title"?: string;
  "crossref-def-title"?: string;
  "crossref-exm-title"?: string;
  "crossref-exr-title"?: string;
  "crossref-fig-prefix"?: string;
  "crossref-tbl-prefix"?: string;
  "crossref-lst-prefix"?: string;
  "crossref-ch-prefix"?: string;
  "crossref-apx-prefix"?: string;
  "crossref-sec-prefix"?: string;
  "crossref-eq-prefix"?: string;
  "crossref-thm-prefix"?: string;
  "crossref-lem-prefix"?: string;
  "crossref-cor-prefix"?: string;
  "crossref-prp-prefix"?: string;
  "crossref-cnj-prefix"?: string;
  "crossref-def-prefix"?: string;
  "crossref-exm-prefix"?: string;
  "crossref-exr-prefix"?: string;
  "crossref-lof-title"?: string;
  "crossref-lot-title"?: string;
  "crossref-lol-title"?: string;
};

export type WebsiteAbout = {
  "image-width"?: string;
  "image-shape"?: ("rectangle" | "round" | "rounded");
  id?: string;
  image?: string;
  links?: (NavigationItem)[];
  template?: ("jolla" | "trestles" | "solana" | "marquee" | "broadside");
};

export type WebsiteListing = {
  "max-items"?: number;
  "page-size"?: number;
  "sort-ui"?: (boolean | (string)[]);
  "filter-ui"?: (boolean | (string)[]);
  "date-format"?: string;
  "max-description-length"?: number;
  "image-placeholder"?: string;
  "image-align"?: ("left" | "right");
  "image-height"?: string;
  "grid-columns"?: number;
  "grid-item-border"?: boolean;
  "grid-item-align"?: ("left" | "right" | "center");
  "table-striped"?: boolean;
  "table-hover"?: boolean;
  "field-display-names"?: SchemaObject;
  "field-types"?: SchemaObject;
  "field-links"?: (string)[];
  "field-required"?: (string)[];
  contents?: MaybeArrayOf<(string | WebsiteListingContentsObject)>;
  categories?: (boolean | ("numbered" | "unnumbered" | "cloud"));
  feed?: (boolean | {
    categories?: MaybeArrayOf<string>;
    description?: string;
    items?: number;
    image?: string;
    language?: string;
    type?: ("full" | "partial");
    title?: string;
  });
  fields?: (string)[];
  id?: string;
  sort?: MaybeArrayOf<string>;
  type?: ("default" | "table" | "grid" | "custom");
  template?: string;
};

export type WebsiteListingContentsObject = {
  author?: MaybeArrayOf<string>;
  date?: string;
  subtitle?: string;
  title?: string;
};

export type CslDate = (string | MaybeArrayOf<number>);

export type CslPerson = (
  | MaybeArrayOf<string>
  | MaybeArrayOf<{ "family-name"?: string; "given-name"?: string }>
);

export type CslNumber = (number | string);

export type CslItem = {
  "abstract-url"?: string;
  "archive-collection"?: string;
  "archive-location"?: string;
  "archive-place"?: string;
  "available-date"?: CslDate;
  "call-number"?: string;
  "chapter-number"?: CslNumber;
  "citation-key"?: string;
  "citation-label"?: string;
  "citation-number"?: CslNumber;
  "collection-editor"?: CslPerson;
  "collection-number"?: CslNumber;
  "collection-title"?: string;
  "container-author"?: CslPerson;
  "container-title"?: string;
  "container-title-short"?: string;
  "editorial-director"?: CslPerson;
  "editor-translator"?: CslPerson;
  "event-date"?: CslDate;
  "event-title"?: string;
  "event-place"?: string;
  "executive-producer"?: CslPerson;
  "first-reference-note-number"?: CslNumber;
  "fulltext-url"?: string;
  "number-of-pages"?: CslNumber;
  "number-of-volumes"?: CslNumber;
  "original-author"?: CslPerson;
  "original-date"?: CslDate;
  "original-publisher"?: string;
  "original-publisher-place"?: string;
  "original-title"?: string;
  "page-first"?: CslNumber;
  "page-last"?: CslNumber;
  "part-number"?: CslNumber;
  "part-title"?: string;
  "pdf-url"?: string;
  "printing-number"?: CslNumber;
  "public-url"?: string;
  "publisher-place"?: string;
  "reviewed-author"?: CslPerson;
  "reviewed-genre"?: string;
  "reviewed-title"?: string;
  "script-writer"?: CslPerson;
  "series-creator"?: CslPerson;
  "supplement-number"?: CslNumber;
  "title-short"?: string;
  "volume-title"?: string;
  "year-suffix"?: string;
  abstract?: string;
  accessed?: CslDate;
  annote?: string;
  archive?: string;
  archive_collection?: string;
  archive_location?: string;
  author?: CslPerson;
  authority?: string;
  chair?: CslPerson;
  compiler?: CslPerson;
  composer?: CslPerson;
  contributor?: CslPerson;
  curator?: CslPerson;
  dimensions?: string;
  director?: CslPerson;
  division?: string;
  doi?: string;
  DOI?: string;
  edition?: CslNumber;
  editor?: CslPerson;
  event?: string;
  genre?: string;
  guest?: CslPerson;
  host?: CslPerson;
  illustrator?: CslPerson;
  interviewer?: CslPerson;
  isbn?: string;
  issn?: string;
  issue?: CslNumber;
  issued?: CslDate;
  ISBN?: string;
  ISSN?: string;
  jurisdiction?: string;
  keyword?: string;
  language?: string;
  license?: string;
  locator?: CslNumber;
  medium?: string;
  narrator?: CslPerson;
  note?: string;
  number?: CslNumber;
  organizer?: CslPerson;
  page?: CslNumber;
  performer?: CslPerson;
  pmcid?: string;
  pmid?: string;
  producer?: CslPerson;
  publisher?: string;
  PMCID?: string;
  PMID?: string;
  recipient?: CslPerson;
  references?: string;
  scale?: string;
  section?: CslNumber;
  source?: string;
  status?: string;
  submitted?: CslDate;
  title?: string;
  translator?: CslPerson;
  type?: (
    | "article"
    | "article-journal"
    | "article-magazine"
    | "article-newspaper"
    | "bill"
    | "book"
    | "broadcast"
    | "chapter"
    | "classic"
    | "collection"
    | "dataset"
    | "document"
    | "entry"
    | "entry-dictionary"
    | "entry-encyclopedia"
    | "event"
    | "figure"
    | "graphic"
    | "hearing"
    | "interview"
    | "legal_case"
    | "legislation"
    | "manuscript"
    | "map"
    | "motion_picture"
    | "musical_score"
    | "pamphlet"
    | "paper-conference"
    | "patent"
    | "performance"
    | "periodical"
    | "personal_communication"
    | "post"
    | "post-weblog"
    | "regulation"
    | "report"
    | "review"
    | "review-book"
    | "software"
    | "song"
    | "speech"
    | "standard"
    | "thesis"
    | "treaty"
    | "webpage"
  );
  url?: string;
  URL?: string;
  version?: CslNumber;
  volume?: CslNumber;
};

export type SmartInclude = ({ text: string } | { file: string });

export type Semver = string;

export type ProjectConfig = {
  "execute-dir"?: ("file" | "project");
  "output-dir"?: string;
  "lib-dir"?: string;
  "pre-render"?: MaybeArrayOf<string>;
  "post-render"?: MaybeArrayOf<string>;
  preview?: ProjectPreview;
  render?: (string)[];
  resources?: MaybeArrayOf<string>;
  title?: string;
  type?: ("default" | "website" | "book" | "site");
};

export type BookProject = ({
  "output-file"?: string;
  "cover-image"?: string;
  "cover-image-alt"?: string;
  author?: MaybeArrayOf<(string | SchemaObject)>;
  abstract?: string;
  appendices?: ChapterList;
  chapters?: ChapterList;
  date?: string;
  description?: string;
  downloads?: MaybeArrayOf<("pdf" | "epub" | "docx")>;
  doi?: string;
  references?: string;
  subtitle?: string;
  sharing?: MaybeArrayOf<("twitter" | "facebook" | "linkedin")>;
  title?: string;
  tools?: (NavigationItem)[];
} & BaseWebsite);
