/*
 * readme.ts
 *
 * The generated `_axe-checks/README.md`: the docs that travel with the
 * artifacts. It exists because nothing else can reach a consumer working in
 * a scanned site's repo — quarto-cli's help layers only load from a
 * quarto-cli checkout, and an agent asked to baseline a finding has only the
 * artifact directory in front of it (observed failing exactly that way,
 * 2026-08-25). So the baseline how-to lives here inline, never as a pointer.
 *
 * Versioning is by regeneration: the README is overwritten on every scan by
 * the build that wrote the neighbouring artifacts, and it documents that
 * build. The one cross-version surface — the hand-written baseline — is
 * guarded by its parser, and the README defers migrations to those error
 * messages.
 *
 * Copyright (C) 2026 Posit Software, PBC
 */

import { AxeFindings, kFindingsVersion, kSignatureScheme } from "./schemas.ts";
import {
  kAxeBaselineFile,
  kDefaultSettle,
  kDefaultThemes,
  kDefaultTimeout,
  kDefaultViewports,
} from "./config.ts";

/** The exact command that produced this scan, reconstructed from the echo. */
export function scanCommand(results: AxeFindings): string {
  const config = results.config;
  const parts = [`quarto call axe ${config.siteDir}`];
  if (config.pages) {
    parts.push(`--pages "${config.pages.join(",")}"`);
  }
  if (config.exclude) {
    parts.push(`--exclude "${config.exclude.join(",")}"`);
  }
  if (config.maxPages !== null) {
    parts.push(`--max-pages ${config.maxPages}`);
  }
  if (config.viewports.join(",") !== kDefaultViewports) {
    parts.push(`--viewports ${config.viewports.join(",")}`);
  }
  if (config.themes.join(",") !== kDefaultThemes) {
    parts.push(`--themes ${config.themes.join(",")}`);
  }
  if (config.timeout !== kDefaultTimeout) {
    parts.push(`--timeout ${config.timeout}`);
  }
  if (config.settle !== kDefaultSettle) {
    parts.push(`--settle ${config.settle}`);
  }
  if (config.failOn) {
    parts.push(`--fail-on ${config.failOn}`);
  }
  return parts.join(" ");
}

/** Render the README that lands beside findings.json and report.md. */
export function renderReadme(results: AxeFindings): string {
  const command = scanCommand(results);
  const partial = results.config.pages || results.config.exclude ||
    results.config.maxPages !== null;
  return `# Quarto axe scan artifacts

Generated by \`quarto call axe\` — **regenerated on every scan; do not
edit.** This file documents the build that wrote the artifacts beside it:

- Quarto ${results.quartoVersion} · axe-core ${
    results.axeVersion ?? "unknown"
  } · \`findings.json\` version ${kFindingsVersion} · signature scheme ${kSignatureScheme}
- generated ${results.generated}

## Regenerate

\`\`\`sh
${command}
\`\`\`
${
    partial
      ? `
**This was a partial scan** — counts describe the subset the flags selected,
not the whole site. Drop \`--pages\`/\`--exclude\`/\`--max-pages\` for the
full picture. A one-page rescan proves an instance is gone, not a systemic
finding.
`
      : ""
  }
If the versions above don't match your installed Quarto, rerun the command:
everything here (this README included) is a scan artifact, and regenerating
is how it stays true.

## What's here

| file | what it is |
|---|---|
| \`findings.json\` | The machine-readable contract: every finding, grouped by root-cause signature, reconciled against the baseline. |
| \`report.md\` | The human summary of the same data. |
| \`cells/*.json\` | Raw axe output per page × viewport × mode cell. Cells accumulate across scans by name — only the most recent **full** scan is a coherent set. |
| \`.gitignore\` | Written by the scanner (\`*\`): this whole directory is a disposable artifact, never committed. |
| \`../${kAxeBaselineFile}\` | The **hand-written, committed** ledger of accepted findings. Lives beside this directory, never inside it: this directory is disposable, the ledger is not. |

Fixes belong in the Quarto **source** — a \`.qmd\`, \`_quarto.yml\`,
\`_brand.yml\`, or a theme \`.scss\` — never in the rendered site directory,
which is overwritten on every render. A finding that repeats across many
pages usually comes from Quarto's own templates (navbar, footer, listings)
and may warrant an upstream \`quarto-dev/quarto-cli\` issue rather than a
local change.

## Working with findings.json

Each entry in \`findings[]\` is one root cause, not one element:

- \`id\` — stable handle (rule + signature hash); "fix \`image-alt-6e3b76\`"
  is a well-defined instruction across runs.
- \`signature\` — the page-independent root-cause key, and the baseline's
  join key.
- \`baselined\` — the switch: act on \`false\`.
- \`impact\`, \`conformance\`, \`helpUrl\` — severity and the WCAG label.
- \`pages\`, \`instances\` — reach (many pages usually means a shared
  source: one fix clears them all); \`occurrences[]\` — real examples, each
  with a CSS \`target\`, an \`html\` excerpt, and the matrix cells it
  reproduced in.

\`notOkCells[]\` lists cells that did not produce a result (timeout, error,
redirect) — those pages are **unverified**, never passing. \`redirects[]\`
lists redirect stubs set aside at discovery (site furniture, not content).

## Accepting a finding (the baseline)

The baseline is deliberately hand-written: every entry exists because someone
decided it and wrote down why. To accept a finding:

1. Copy the finding object out of \`findings.json\`.
2. Paste it into the \`findings\` array of \`../${kAxeBaselineFile}\`
   (create the file as \`{ "findings": [] }\` if it doesn't exist).
3. Trim it to the fields that matter and add a \`note\`:

\`\`\`jsonc
{
  "signatureScheme": ${kSignatureScheme},
  "findings": [
    {
      "signature": "aria-allowed-role :: .navbar-toggler",  // required: the join key
      "pages": [],             // required: [] = accepted site-wide (right for
                               // chrome); a listed pages array accepts ONLY
                               // those pages and re-alerts anywhere else
      "impact": "minor",       // required: impact AT acceptance — if the
                               // finding later escalates past this, it
                               // re-alerts as new
      "note": "tracked upstream: quarto-cli#14615",  // required, non-empty:
                               // the why. Surfaced back in report.md.
      "id": "aria-allowed-role-6c6fc2",  // optional reviewer context
      "rule": "aria-allowed-role"        // optional reviewer context
    }
  ]
}
\`\`\`

Extra fields pasted from the finding are tolerated; misspelled fields are
errors (the ledger is validated on read — trust its messages, they explain
migrations too). One entry per signature: a second entry for a signature you
already accepted is an error, not a merge — to accept it on more pages, add
them to that entry's \`pages\`.

Which ledger a problem belongs in: if the author *chose*
the inaccessibility as part of a lesson, that is a future exclude-in-source
case; if someone should eventually fix it — including upstream library
defects — it belongs here, with the tracking link in the \`note\`.

Stale entries (accepted findings a scan no longer sees) are reported in
\`report.md\` and \`findings.json\`, never auto-pruned: prune by hand after a
**full-site** scan, since a subset scan can't tell "fixed" from "not
scanned".
`;
}
