#!/bin/sh

if [[ $EUID -eq 0 ]]; then
ln -fs $2/bin/quarto /usr/local/bin/quarto
else

# write path to zshenv
EXPORTLINE='export PATH="'$2'/bin:$PATH"'
EXPORTFILE=~/.zshenv

# Add the path to the zshenv if it doesn't already exist
grep -qxF "$EXPORTLINE" "$EXPORTFILE" || echo "$EXPORTLINE" >> "$EXPORTFILE"

# try creating symlink, its ok if this doesn't work
ln -fs $2/bin/quarto /usr/local/bin/quarto

fi

exit 0

