#' ---
#' title: "A report generated from a pure R script"
#' ---
#'
#' This is a report generated by `knitr::spin()`.
#'
#' Let's try some **knitr** options:

#+ echo=FALSE, fig.width=7
#  This is a normal R comment.
plot(cars)

#' Now write an inline value. We know the value of $\pi$ is
{{ pi }}
#' .
#'
#' Finally please note that all roxygen comments are
#' optional. You do not need chunk options, either,
#' unless you want more control over the output
