function Div(div)
  assert(quarto.utils.match("Div")(div) == div)
  assert(quarto.utils.match("Div/[1]")(div) == div.content[1])
  assert(quarto.utils.match("Div/[1]/Para")(div) == div.content[1])
  assert(quarto.utils.match("Div/[1]/Para/[1]")(div) == div.content[1].content[1])
  assert(quarto.utils.match("[1]/[1]")(div) == div.content[1].content[1])
  assert(not quarto.utils.match("Para/[1]/[1]")(div))

  local lst = quarto.utils.match("{Div}/[1]/{Para}/[1]/{Str}")(div)
  assert(lst[1] == div)
  assert(lst[1].t == "Div")
  assert(lst[2] == div.content[1])
  assert(lst[2].t == "Para")
  assert(lst[3] == div.content[1].content[1])
  assert(lst[3].t == "Str")
  
  assert(quarto.utils.match(function(node) return node.content[1].content[1] end)(div) == div.content[1].content[1])
  assert(quarto.utils.match("Div", "[1]")(div) == div.content[1])
  assert(quarto.utils.match("Div", "[1]", "Para")(div) == div.content[1])
  assert(quarto.utils.match("Div", "[1]", "Para", "[1]")(div) == div.content[1].content[1])
  assert(quarto.utils.match("[1]", "[1]")(div) == div.content[1].content[1])
end