#!/bin/bash


if [ -f "$FILE" ]; then
    echo "$FILE exists."
fi

#Environment may provide an import map
if [ -n "$QUARTO_IMPORT_MAP" ]; then
	QUARTO_IMPORT_ARGMAP=--importmap="${QUARTO_IMPORT_MAP}"
fi 

# Environment can point deno at another entry point (e.g. the typescript file)
if [ -z "$QUARTO_SRC" ]; then
	QUARTO_SRC=quarto.js
fi


# Figure out the path that we're using
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  QUARTO_PATH="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
export QUARTO_PATH="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
export R_PATH="/Library/Frameworks/R.framework/Resources/bin/"

QUARTO_DENO_OPTIONS="--unstable --allow-read --allow-write --allow-run --allow-env"
${QUARTO_PATH}/deno run ${QUARTO_DENO_OPTIONS} ${QUARTO_IMPORT_ARGMAP} ${QUARTO_PATH}/${QUARTO_SRC} $@