#!/bin/bash
export QUARTO_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. >/dev/null 2>&1 && pwd )"

echo $QUARTO_PATH

DENO_OPTIONS="--unstable --allow-read --allow-write --allow-run --allow-env"
${QUARTO_PATH}/bin/deno run ${DENO_OPTIONS} ${QUARTO_PATH}/bin/quarto.js $@