/*
* format-language.ts
*
* JSON Schema for Quarto's FormatLanguage
*
* Copyright (C) 2021 by RStudio, PBC
*
*/

import {
  idSchema as withId,
  objectSchema as objectS,
  StringSchema as StringS,
} from "./common.ts";

import {
  kCalloutDangerCaption,
  kCalloutImportantCaption,
  kCalloutNoteCaption,
  kCalloutTipCaption,
  kCalloutWarningCaption,
  kCodeSummary,
  kCodeToolsHideAllCode,
  kCodeToolsMenuCaption,
  kCodeToolsShowAllCode,
  kCodeToolsSourceCode,
  kCodeToolsViewSource,
  kCopyButtonTooltip,
  kCrossrefCnjPrefix,
  kCrossrefCnjTitle,
  kCrossrefCorPrefix,
  kCrossrefCorTitle,
  kCrossrefDefPrefix,
  kCrossrefDefTitle,
  kCrossrefEqPrefix,
  kCrossrefExmPrefix,
  kCrossrefExmTitle,
  kCrossrefExrPrefix,
  kCrossrefExrTitle,
  kCrossrefFigPrefix,
  kCrossrefFigTitle,
  kCrossrefLemPrefix,
  kCrossrefLemTitle,
  kCrossrefLofTitle,
  kCrossrefLolTitle,
  kCrossrefLotTitle,
  kCrossrefLstPrefix,
  kCrossrefLstTitle,
  kCrossrefPrfTitle,
  kCrossrefPrpPrefix,
  kCrossrefSecPrefix,
  kCrossrefTblPrefix,
  kCrossrefTblTitle,
  kCrossrefThmPrefix,
  kCrossrefThmTitle,
  kRepoActionLinksEdit,
  kRepoActionLinksIssue,
  kRepoActionLinksSource,
  kSearchClearButtonTitle,
  kSearchCopyLinkTitle,
  kSearchDetatchedCancelButtonTitle,
  kSearchHideMatchesText,
  kSearchMatchingDocumentsText,
  kSearchMoreMatchText,
  kSearchNoResultsText,
  kSearchSubmitButtonTitle,
  kSectionTitleFootnotes,
  kTocTitleDocument,
  kTocTitleWebsite,
} from "../../config/constants.ts";

export const formatLanguageSchema = withId(
  objectS({
    properties: {
      [kTocTitleDocument]: StringS,
      [kTocTitleWebsite]: StringS,
      [kCalloutTipCaption]: StringS,
      [kCalloutNoteCaption]: StringS,
      [kCalloutWarningCaption]: StringS,
      [kCalloutImportantCaption]: StringS,
      [kCalloutDangerCaption]: StringS,
      [kSectionTitleFootnotes]: StringS,
      [kCodeSummary]: StringS,
      [kCodeToolsMenuCaption]: StringS,
      [kCodeToolsShowAllCode]: StringS,
      [kCodeToolsHideAllCode]: StringS,
      [kCodeToolsViewSource]: StringS,
      [kCodeToolsSourceCode]: StringS,
      [kRepoActionLinksEdit]: StringS,
      [kRepoActionLinksSource]: StringS,
      [kRepoActionLinksIssue]: StringS,
      [kSearchNoResultsText]: StringS,
      [kCopyButtonTooltip]: StringS,
      [kSearchMatchingDocumentsText]: StringS,
      [kSearchCopyLinkTitle]: StringS,
      [kSearchMoreMatchText]: StringS,
      [kSearchHideMatchesText]: StringS,
      [kSearchClearButtonTitle]: StringS,
      [kSearchDetatchedCancelButtonTitle]: StringS,
      [kSearchSubmitButtonTitle]: StringS,
      [kCrossrefFigTitle]: StringS,
      [kCrossrefTblTitle]: StringS,
      [kCrossrefLstTitle]: StringS,
      [kCrossrefThmTitle]: StringS,
      [kCrossrefLemTitle]: StringS,
      [kCrossrefCorTitle]: StringS,
      [kCrossrefPrfTitle]: StringS,
      [kCrossrefCnjTitle]: StringS,
      [kCrossrefDefTitle]: StringS,
      [kCrossrefExmTitle]: StringS,
      [kCrossrefExrTitle]: StringS,
      [kCrossrefFigPrefix]: StringS,
      [kCrossrefTblPrefix]: StringS,
      [kCrossrefLstPrefix]: StringS,
      [kCrossrefSecPrefix]: StringS,
      [kCrossrefEqPrefix]: StringS,
      [kCrossrefThmPrefix]: StringS,
      [kCrossrefLemPrefix]: StringS,
      [kCrossrefCorPrefix]: StringS,
      [kCrossrefPrpPrefix]: StringS,
      [kCrossrefCnjPrefix]: StringS,
      [kCrossrefDefPrefix]: StringS,
      [kCrossrefExmPrefix]: StringS,
      [kCrossrefExrPrefix]: StringS,
      [kCrossrefLofTitle]: StringS,
      [kCrossrefLotTitle]: StringS,
      [kCrossrefLolTitle]: StringS,
    },
    description: "be a format language description object",
  }),
  "format-language",
);
