# Gathers baseline performance data for the bundled version of Quarto
name: Test Placeholder
on:
  workflow_dispatch:
jobs:
  build-launcher:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest }
          - { os: macOS-latest }
          - { os: ubuntu-latest }
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0

      - name: Build Launcher
        uses: ./.github/workflows/actions/launcher
