# Gathers baseline performance data for the bundled version of Quarto
name: Test Placeholder
on:
  workflow_dispatch:
jobs:
  build-launcher:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest }
          - { os: macOS-latest }
          - { os: ubuntu-latest }
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.63.0
          override: true
          components: rustfmt, clippy
      - run: cargo build --release --all-features --manifest-path package/launcher/Cargo.toml
      - shell: bash
        run: |
          mkdir -p package/dist/bin
          cp package/launcher/target/release/quarto package/dist/bin/quarto
