# Tests a broad set of Quarto functionality that users are likely to encounter.
# A failure indicates some signficant portion of functionality is likely to be broken.
name: Parallel Smokes Tests
on:
  workflow_dispatch:

jobs:
  jobs-matrix:
    runs-on: ubuntu-latest
    outputs:
      buckets: ${{ steps.tests-buckets.outputs.buckets }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Create Job for tests
        id: tests-buckets
        run: |
          echo "buckets=$(run-parallel-tests.sh -n=10 --dry-run | jq -rc '.[][] |= .name | map_values(join(" ")) | { buckets: . }')" >> "$GITHUB_OUTPUT"
        working-directory: tests
      - name: Read buckets
        run: |
          echo ${{ fromJSON(steps.tests-buckets.outputs.buckets) }} | jq .

  run-smoke-tests:
    # needs: jobs-matrix
    #    strategy:
    #      fail-fast: false
    #      matrix:
    #        tests:
    #          - [
    #              "./smoke/yaml-intelligence/yaml-intelligence.test.ts",
    #              "./smoke/render/render-citeproc.test.ts",
    #            ]
    #          - [
    #              "./smoke/extensions/extension-render-project.test.ts",
    #              "./smoke/jats/render-jats.test.ts",
    #            ]
    uses: ./.github/workflows/test-smokes.yml
    with:
      buckets: "./smoke/yaml-intelligence/yaml-intelligence.test.ts ./smoke/render/render-citeproc.test.ts"
