# Tests a broad set of Quarto functionality that users are likely to encounter.
# A failure indicates some signficant portion of functionality is likely to be broken.
name: Parallel Smokes Tests
on:
  workflow_dispatch:

jobs:
  jobs-matrix:
    runs-on: ubuntu-latest
    outputs:
      BUCKETS: ${{ steps.tests-buckets.outputs.BUCKETS }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Create Job for tests
        id: tests-buckets
        run: |
          echo "BUCKETS=$(./run-parallel-tests.sh -n=10 --dry-run | jq -rc '.[][] |= .name | map_values(join(" ")) | { buckets: ., num: to_entries | map( (.value = "\(1+.key)" ) | .value)}')" >> "$GITHUB_OUTPUT"
        working-directory: tests
      - name: Read buckets
        run: |
          echo ${{ steps.tests-buckets.outputs.BUCKETS }}

  check-matrix:
    runs-on: ubuntu-latest
    needs: jobs-matrix
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml

      - name: Check matrix definition
        run: |
          matrix='${{ needs.jobs-matrix.outputs.BUCKETS }}'
          echo $matrix
          echo $matrix | jq .
          echo $matrix | json2yaml
  run-smoke-tests:
    # needs: jobs-matrix
    name: Running Tests buckets ${{ matrix.num }}
    strategy:
      fail-fast: false
      matrix:
        num: [1, 2]
        buckets:
          - "./smoke/yaml-intelligence/yaml-intelligence.test.ts ./smoke/render/render-citeproc.test.ts"
          - "./smoke/extensions/extension-render-project.test.ts ./smoke/jats/render-jats.test.ts"
    uses: ./.github/workflows/test-smokes.yml
    with:
      buckets: ${{ matrix.buckets }}
